name = "Symphony of the Night"
home = "https://discord.com/channels/731205301247803413/1108439196156317818"

[versions]
"0.8.0-beta" = { url = "https://github.com/fdelduque/Archipelago/releases/download/b0800/sotn.apworld" }
